### ISSUE TITLE
box-reflect

### ISSUE THREAD

**Issue by anyotherway** [y0ssar1an/CSS3#101]
CSS3 does not support box-reflect or -webkit-box-reflect used by at least 30% of web users. 
Here is MDN/Microsoft non-standard:
https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-box-reflect
Here is WebKit standard:
https://webkit.org/blog/182/css-reflections/
Here is CanIUse standard:
https://caniuse.com/#feat=css-reflections
Here is sample of typical text reflection, valid code:
Sample VALID Code 
color: red; background: white; box-reflect: below 5px -webkit-gradient(linear, left top, left bottom, from(transparent), color-stop(0.5, transparent), to(blue)) 
Result for Sublime Text is CODE WIPEOUT, lines of valid code being filled with either red code blocks or plain white text. This may also relate to failed Sublime support. Sublime Team notified. 
![screen shot 2018-04-22 at 04 48 13](https://user-images.githubusercontent.com/11430826/39098636-ab539744-4622-11e8-83a9-d0660b85740d.png)
Safari has issue where unique text color is not possible, parent element color only is allowed for now. Color normalization request to Safari Team...

**Comment by y0ssar1an** [comment]
I'm sorry, but it appears `box-reflect` is not in any W3C spec, which is what I base CSS3 on. It works on Chrome and Safari, but not Firefox or Edge. The [MDN link](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-box-reflect) suggests using [`element()`](https://developer.mozilla.org/en-US/docs/Web/CSS/element), which _is_ on the standards track. Unfortunately, `element()` is [only supported by Firefox](https://caniuse.com/#feat=css-element-function) right now, so I'm afraid I don't have a solution for you 😢. I don't want to commit to supporting nonstandard CSS, because then I'll have to add a gazillion little browser-specific properties, most of which shouldn't be used. Sorry!

Thank you for the helpful links in researching this.
