### ISSUE TITLE
"currentcolor" keyword should be "currentColor"

### ISSUE THREAD

**Issue by FeBe95** [y0ssar1an/CSS3#111]
The title says it all.
I don't know if it really makes a difference in any browser but the official spelling is `currentColor`.

**Comment by y0ssar1an** [comment]
Sorry for taking so long to research this. Here's what I've learned.

It's `currentColor` in [the Color Module Level 3 spec](https://www.w3.org/TR/css-color-3/#currentcolor).
It's `currentcolor` in [the Color Module Level 4 spec](https://www.w3.org/TR/css-color-4/#valdef-color-currentcolor).

I guess they changed it because currentColor` looked out of place as the only camelCased keyword.

Thankfully, [both values are accepted by all the modern browsers](https://caniuse.com/#search=currentcolor). I think `currentcolor` should be preferred, since it's the more forward-looking spec. Thanks for prompting me to research this 👍
