### ISSUE TITLE
Support for tailwindCSS directives

### ISSUE THREAD

**Issue by brielov** [y0ssar1an/CSS3#125]
It would be nice to have syntax highlighting for `@tailwind` and `@apply` directives .

<img width="525" alt="Screen Shot 2020-04-21 at 16 27 52" src="https://user-images.githubusercontent.com/42145089/79905716-10c42800-83ed-11ea-99f9-43f66c6cd206.png">

**Comment by y0ssar1an** [comment]
There are a lot of CSS frameworks. To keep the scope of this project limited, I've decided to only support CSS for which there is a W3C spec. The only exception I've made in the past was for [PostCSS-cssnext](https://cssnext.github.io/). This wasn't really an exception, because all the cssnext features had draft W3C specs.

Sorry to disappoint 🙁. I'm sure tailwind is a great framework.
