### ISSUE TITLE
Please release validator.py as a separate package

### ISSUE THREAD

**Issue by aziz** [y0ssar1an/CSS3#17]
`validator.py` registers an extremely expensive event, `on_selection_modified_async`, which runs all the time, every where and in general just slows down ST. 
I tend to avoid any package that registers `on_selection_modified`, `on_selection_modified_async`, `on_modified` and `on_modified_async` since these are firing quite frequently. 
I would rather have the validator as a SublimeLinter plugin since all those linting and validating events are grouped into one.

**Comment by y0ssar1an** [comment]
You're exactly right about `on_selection_modified_async`. I was leery about using it, but I couldn't see a way to avoid it. If you know of a better way to display the error message in the status bar when a user selects a line with an error, please enlighten me.

I'm not sure how I feel about making it a separate package. I like the idea of giving people a choice, but a lot of the people using it probably discovered it accidentally when they were looking for better CSS highlighting.

I will say that the current implementation of the validator is not great. I'm going to make a second pass over it soon. Maybe I can optimize it or remove the `on_selection_modified_async` call entirely. In any case, thank you for calling attention to this.

**Comment by druellan** [comment]
Thanks @y0ssar1an for the explanation. Any improvements on this? Is there a way to totally disable the validator (without forking the project)? As @aziz, I'm using SublimeLinter, and I don't need another validation method (even when CSSlint is kinda outdated).

**Comment by y0ssar1an** [comment]
Sorry, I haven't been working on CSS3 at all lately. I'm swamped for the next couple of months, but I definitely plan to resume regular work on it.

Here's how you can disable the validator. You're going to unzip the package, delete the validator, and copy the contents to a new directory in `Sublime Text 3/Packages`.

1) Copy `Sublime Text 3/Installed Packages/CSS3.sublime-package` to a temporary directory. It doesn't matter which directory. It's just a place to unzip a file.
2) Delete `Sublime Text 3/Installed Packages/CSS3.sublime-package`.
3) `.sublime-package` files are really just `.zip` files with a custom extension. Change the extension to `.zip` and unzip it with your favorite program.
4) Delete `validator.py` from the folder you just unzipped.
5) Make this directory `Sublime Text 3/Packages/CSS3`.
6) Copy the all the unzipped files into that directory. You should be looking at this (notice how `validator.py` is gone):
![image](https://cloud.githubusercontent.com/assets/1250684/9052561/ded230b2-3a1d-11e5-9857-2d0aa4d29ddb.png)

There are two small downsides. First, when you Package Control: Upgrade Package, it may tell you that CSS3 needs to be updated. Ignore it. Second, you can't update CSS3 through Package Control anymore. That shouldn't be a problem because CSS3 won't be updated for the next few months. Eventually there will be a big update to CSS3 (complete rewrite in the new `sublime-syntax` format), so you'll want to check back here in a few months to see if it's been released.

**Comment by druellan** [comment]
Thanks @y0ssar1an to take the time on this. I was not asking for such a detailed explanation, but I appreciate it.
I have two ST3 installations, one "stable" for real coding, and the other for experimentation, so, I'm going to leave your package on the "experimental" one, to check your progress on this.
The validation thing is not such a big issue, but since I'm already using some heavy plugins like SublieLinter, Color Highlighter, GitGutter, etc, I'm trying no to avoid any kind of delay.

**Comment by y0ssar1an** [comment]
I've decided to break the validator into a separate package in the 2.0 release. I still have weeks of work to do, but this change is coming.

**Comment by y0ssar1an** [comment]
Version 2.0.0 is out. The validator has been removed. It took me a long time to see your wisdom @aziz, but I think the plugin is better for it. The validator will return in a separate package (no ETA sorry).
