### ISSUE TITLE
Highlighting issues

### ISSUE THREAD

**Issue by FeBe95** [y0ssar1an/CSS3#18]
* "-webkit-tap-highlight" and "-webkit-touch-callout" are not highilighted
* no highlighting of following selector when leaving out the last semicolon in a css block (also in minified css files without line breaks):
![st3 css highlight bug](https://cloud.githubusercontent.com/assets/7470739/6315640/709513fc-ba08-11e4-88c3-80e905bc353c.png)

* 
"-ms-user-select", "-moz-user-select", "-webkit-user-select" are valid css [reference: http://caniuse.com/#feat=user-select-none]
![st3 css highlight invalid](https://cloud.githubusercontent.com/assets/7470739/6315760/d343f8ac-ba0c-11e4-98b0-a0f3ccdb034a.png)
* "appearance" not highlighted/wrongly marked as invalid [reference: http://caniuse.com/#feat=css-appearance] 
![st3 css highlight invalid 2](https://cloud.githubusercontent.com/assets/7470739/6315768/3fc87cdc-ba0d-11e4-8225-8dd1559ae4ef.png)

* Pseudo-elements and Pseudo-classes shouldn't be the same color as class-selectors
![st3 css highlight color](https://cloud.githubusercontent.com/assets/7470739/6315702/ff570e68-ba0a-11e4-9bda-b3aebebfc136.png)

That's it for now ;)

**Comment by y0ssar1an** [comment]
[`-webkit-tap-highlight-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Webkit_Extensions#Proprietary_WebKit-prefixed_entities_(do_not_use_on_Web_sites)) and [`-webkit-touch-callout`](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-touch-callout) are non-standard properties that are not on the standards track. My policy is to only highlight prefixed properties on the standards track (meaning they appear in a draft CSS spec somewhere). You're still totally free to use them, of course. If they ever get added to a CSS spec, as often happens with prefixed properties, I'll add them in a heartbeat.

The highlighter will break without the trailing semicolon at the end of every declaration block. This means minified CSS won't highlight correctly, and that sucks. Including the semicolon is a [best practice](http://google-styleguide.googlecode.com/svn/trunk/htmlcssguide.xml?showone=Declaration_Stops#Declaration_Stops) for un-minified CSS. The real reason it's required, though, is that syntax highlighters work by parsing code with regular expressions (Yes, that's a terrible idea, but that's how they work in most text editors). The regexes I wrote need that semicolon to be there. Otherwise, the highlighter will become confused about whether it's in a declaration block, a selector, a media feature, or some other part of CSS. It's possible to change the property/value regexes to look for a trailing semicolon __or__ a closing curly brace. I tried several variations and they all broke in worse ways. So, sorry about this.

`user-select` was explicitly dropped from the CSS spec, but there is no standards-based property to replace it. There's been [discussion about bringing it back](https://lists.w3.org/Archives/Public/www-style/2014Dec/0082.html) to the CSS basic user interface spec, but AFAIK nothing has been decided. The highlighter is doing it's job by notifying you that there's an issue with `user-select`. Nothing is stopping you from using it. Just be aware that it behaves inconsistently across browsers.

`appearance` was also [explicitly dropped](http://www.w3.org/TR/css3-ui/#changes-list) from the spec. I don't have any more information than that. Sorry.

I agree that pseudo-classes/elements should be different colors than classes. The way syntax coloring works is that my syntax highlighter assigns "scopes" (labels) to chunks of text. Themes like Monokai or Solarized assign colors to those scopes. I have a limited vocabulary of scope names to choose from ([see 12.4 here](http://manual.macromates.com/en/language_grammars)). Most of these scope names don't make any sense for CSS. This is a legacy system that Sublime inherited from TextMate, because the Sublime author wanted to be compatible with TextMate themes. I'll take a second look at the scope name I'm assigning to pseudo-classes and pseudo-elements, but the existing scope name may be the least worst choice.

**Comment by FeBe95** [comment]
Wow, thanks for your extensive research and detailed feedback!
