### ISSUE TITLE
max-width value none isn't highlighted

### ISSUE THREAD

**Issue by pi241a** [y0ssar1an/CSS3#26]
`none` should be highlighted. 

![image](https://cloud.githubusercontent.com/assets/4296393/7336381/133f0f58-ebb0-11e4-8bd5-3912a046ec59.png)

MDN and W3C say that `none` is a valid value for `max-width`.

https://developer.mozilla.org/es/docs/Web/CSS/max-width
http://www.w3.org/wiki/CSS/Properties/max-width

**Comment by y0ssar1an** [comment]
The [latest draft of the CSS basic box model spec](http://dev.w3.org/csswg/css-box-3/) doesn't include `none` as a value of `max-width`, but it carries this lovely banner which defers to CSS2.1 while the draft is being rewritten.

![image](https://cloud.githubusercontent.com/assets/1250684/7339958/f99c9620-ec35-11e4-8494-170359a61fc9.png)

That spec does have `none` as a value of max-width, so it should be highlighted. Good catch!

Fixed in v1.2.14
