### ISSUE TITLE
No Syntax Highlighting of the First Element Within a Media Query in Sublime Text 3

### ISSUE THREAD

**Issue by polarizeme** [y0ssar1an/CSS3#29]
Heya.

I've noticed that for some reason the styling of the first element within a media query (in Sublime Text 3) tends to leave it completely unhighlighted for syntax. Outside of a media query seems fine.

Quite simply, something like this works fine:
```
/* HEADER */
header {
	overflow: hidden;
}
```

But something like this leaves "header" unstyled according to syntax:
```
@media all and (min-width: 240px) {
	/* HEADER */
	header {
		overflow: hidden;
        }
}
```

Here are some images to show it in practice:

![screen shot 2015-05-12 at 12 34 42 pm](https://cloud.githubusercontent.com/assets/2906212/7594008/890d6f2c-f8a3-11e4-95d0-96cd5adb3d00.png)

![screen shot 2015-05-12 at 12 35 29 pm](https://cloud.githubusercontent.com/assets/2906212/7594011/91984130-f8a3-11e4-85db-1e2a6e281f51.png)

If you have any questions or need anything clarified, just let me know. =]

Cheers and thanks for the work you've put into this!

**Comment by polarizeme** [comment]
Well shit.

Looks like this is a longstanding issue. Feel free to close it out if you're unable to address it. I'LL JUST GO CRY AT MY DESK. ;]

Cheers!

**Comment by y0ssar1an** [comment]
Yes, this is [the most annoying bug in CSS3](https://github.com/y0ssar1an/CSS3#known-issues). I tried several times to fix it, but always ended breaking something else even worse. The good news is that the latest dev builds of Sublime Text 3 introduce [a totally new system for syntax definitions](http://www.sublimetext.com/docs/3/syntax.html), so I'll be rewriting the syntax highlighter from scratch. That should hopefully kill this bug once and for all. The bad news is it's going to take me a long time. The new system is much better than the old system, so hopefully it's worth the wait. In the mean time, sorry for the grief it's causing you! I'll keep this issue open because it describes the issue very well.

**Comment by polarizeme** [comment]
Grief? Nah. Once I realized it was a bug and that I wasn't crazy, it was easy to ignore. Besides, it's better than all the white highlighting you get *without* CSS3 installed. 

For real, cheers for the effort you've put into this. using it has been lovely. Good luck on the rewrites!

**Comment by jsilvermist** [comment]
The new version of the built-in CSS Syntax in Sublime now supports media queries and fixes this kind of bug, would it be possible to source from that to make fixing this easier?

**Comment by y0ssar1an** [comment]
Unfortunately, I can't copy the rules in the default CSS package. The CSS3 syntax definition is just too different. Fixing this bug will have to wait until I rewrite the entire thing in `sublime-syntax`.

**Comment by y0ssar1an** [comment]
At long last, this bug is dead. Version 2.0.0 is out, with a completely rewritten syntax highlighter.
