### ISSUE TITLE
Disable CSS of Sublime Text 3 get an error

### ISSUE THREAD

**Issue by davinma** [y0ssar1an/CSS3#32]
After installed CSS3, when I Disable CSS of Sublime Text 3, which popuped an error but only once. I can't show it again. So strange?

**Comment by davinma** [comment]
Unfortunately, every time when I will install it, it said something wrong in CSS3...

**Comment by y0ssar1an** [comment]
I can't be sure without more information, but I suspect the problem is that you had a file open with the syntax set to `CSS` when `CSS` was disabled. 

![image](https://cloud.githubusercontent.com/assets/1250684/8011195/80e2855a-0b6b-11e5-8b8f-e4ca46f02590.png)

If you have CSS3 installed, try cmd+shift+p (mac/linux) / ctrl+shift+p (windows) and `Set Syntax: CSS3` to switch to the new syntax highlighter.

If that doesn't fix the problem, could you please screenshot the error message and post it here?
