### ISSUE TITLE
Auto-complete, move the cursor to the right side of the semi-colon.

### ISSUE THREAD

**Issue by MuTLY** [y0ssar1an/CSS3#37]
Here's a suggestion because I think this is kind of annoying.

When I try to auto-complete something, say

    margin: auto;

Pressing the TAB key auto-completes like this:

    margin: |;

With the cursor blinking to the left side of the semi-colon. Then I type something, then I press the right arrow, then I press ENTER for the next line.

How about, after a few milliseconds, move the cursor to the right side of the semi-colon? Or move it when the plugin activates its lint? Is that possible? Do you think that would help with the workflow?

OR, is there a way to just disable the auto-adding of the semi-colon and let the user do that? Reason, tough subjective, it's faster to type a semi-colon than to chase the right arrow key ;)

Great job on your plugin!

**Comment by variadico** [comment]
Interestingly, when you autocomplete something like `url()`, you can type `)` to skip over the closing parenthesis. Also, if you autocomplete the single quotes in `url('')`, again pressing `'` will skip over the closing single quote.

I wonder if it would be possible to make it so that pressing the semi-colon key moves the cursor to the right of the terminating semi-colon.

I agree. The right-arrow key is ssssooo far away. :smile_cat: (This is why I still use Vim.)

**Comment by jonathanholvey** [comment]
Typing a second quote (single or double) will skip over the autocompleted one, but only inside `url()`. Otherwise the second quote is duplicated like this:

`content: "abcd"|"`

The behaviour of the default CSS package is to skip over all autocompleted punctuation, so I hope it will be an easy fix.

**Comment by y0ssar1an** [comment]
I finally understand this. I'm very sorry for taking so long on this issue, but I believe it's fixed in 1.2.19. Pressing `;` at the end of the property should jump over the semicolon. You shouldn't have to use the arrow keys anymore.

The update should be available on Package Control in less than an hour. If you have time, please give it a try and let me know if it works as desired.

**Comment by y0ssar1an** [comment]
Fixed in v1.2.19
