### ISSUE TITLE
user-select property

### ISSUE THREAD

**Issue by mohamadnorouzi20** [y0ssar1an/CSS3#40]
user-select property with it's browser prefixes are not supported

**Comment by yisibl** [comment]
+1

**Comment by y0ssar1an** [comment]
`user-select` was left-out because it was non-standard and not on the standards track when CSS3 was written. This was surprising to most people, because it was well-supported by browsers. As of Sep 22nd, 2015, it has been added to the [CSS Basic User Interface Module Level 4](http://www.w3.org/TR/2015/WD-css-ui-4-20150922/) spec, so it should be added to CSS3. Thank you for bringing up the issue and making me look into it.

**Comment by yisibl** [comment]
> "But", you might object, "I saw things like CSS4 Images, or Selectors 4! Aren't they part of CSS4?".
No. As I just said, there is no CSS4. ^_^

So in any case, you should support this property.

**Comment by y0ssar1an** [comment]
Agreed :)

**Comment by t3db0t** [comment]
Hah, just noticed this—looking forward to adding support ;)

**Comment by y0ssar1an** [comment]
I just pushed out an update that adds support for `user-select`, and the rest of the changes in CSS Basic User Interface Module Level 4. Thanks to all for raising this issue.
