### ISSUE TITLE
spaces between property name and the colon

### ISSUE THREAD

**Issue by mohamadnorouzi20** [y0ssar1an/CSS3#41]
adding spaces between property name and the colon makes the value color go away.

**Comment by y0ssar1an** [comment]
To avoid highlighting mistakes caused by rules accidentally matching the wrong text, CSS3 uses a regex feature called look-behind. Here's an example from the `animation` property.
```
value-animation:
  begin: (?<=animation:)
  # regexes for matching animation values here
  end: (?=[;)])
```
The rules for matching/highlighting `animation` values will only be applied to text that's immediately preceded by the pattern `animation:` (no space). Look-behind is great because it makes the regexes highly specific and prevents mismatches. Unfortunately, it can't match zero or more spaces before the `:`. This pattern won't work: `(?<=animation\s*:)`.

So that's the technical reason, but there's also the philosophical reason that I think individual stylistic preferences hurt code readability. The Google CSS Style Guide [recommends against putting a space before the colon](https://google.github.io/styleguide/htmlcssguide.xml#Selector_and_Declaration_Separation).

If this really bothers you, I could be persuaded to try to remove the rule. What do you think?

**Comment by mohamadnorouzi20** [comment]
the reason I asked this is because I use the AlignTab package and it puts spaces between the property-name and the colon.

you can ask sublime developers how they did it in their own css package.

**Comment by y0ssar1an** [comment]
The [default CSS package](https://github.com/sublimehq/Packages/tree/master/CSS) is very crude. The regexes in CSS3 are much more specific, making it less prone to mismatches and breakages compared to the default CSS package. The cost of this specificity is requiring that there be no space before the colon.
