### ISSUE TITLE
autocomplete suggestions

### ISSUE THREAD

**Issue by bergeg** [y0ssar1an/CSS3#59]
before(1.3.3), pressing ctrl+space showed property suggestions
![123](https://cloud.githubusercontent.com/assets/3939845/17293690/838b31bc-57fa-11e6-914f-875ebd922b9b.jpg)
now(2.0.0), pressing ctrl+space suggests everything
![321](https://cloud.githubusercontent.com/assets/3939845/17293720/a6f9c2ee-57fa-11e6-951d-45df5cf34326.jpg)

fixable?

**Comment by y0ssar1an** [comment]
I haven't been able to reproduce this. On my machine, 2.0.0 produces the top output when you press Ctrl+Space. Can you check your console (Ctrl+` on OS X)? Do you see any Python tracebacks or anything that looks suspicious? When the completions script crashes, Sublime will fall back to it's local symbol index for completions. That might be what's happening.

Also, have you restarted Sublime since the update?

**Comment by bergeg** [comment]
i had to remove old css3 and install new one to fix the issue

**Comment by y0ssar1an** [comment]
Ok. If anyone else has this issue, I'll recommend they remove the plugin completely and reinstall. Thanks for letting me know!
