### ISSUE TITLE
linear-gradient old webkit prefix gets some parenthesis flagged

### ISSUE THREAD

**Issue by diegocanal** [y0ssar1an/CSS3#60]
Hi, first, congratulations and thanks for such a great package!

I have not seen on the [list of bad CSS properties](https://gist.github.com/y0ssar1an/bb95223148e486acbe7a#file-bad_css) the prefixed rules for the `linear-gradient()` function. The point is that CSS3 is flagging some parenthesis in the **old** webkit prefix, for example:

> `background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0, rgba(2, 166, 207, 1)), color-stop(1, rgba(0, 146, 183, 1)));`

Another example:

> `background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0, #ffffff), color-stop(1, #f0f4f5));`

I do not know your criteria for qualifying a property as a "bad" one. In case it is of any help, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient#Cross-browser_gradients):

> The -moz- prefixed rules are used for compatibility with older versions (Fx 3.6 to Fx 15). The -webkit-prefix is the only one that still needs to be included for Android 4.3-, iOS up to 6.1, and Safari 6. 

I enclose a couple of screenshots down below:

![screen shot 2016-08-01 at 13 18 25](https://cloud.githubusercontent.com/assets/3908213/17292526/f8cab8a4-57ea-11e6-9c16-de9d802b1214.png)

![screen shot 2016-08-01 at 14 54 43](https://cloud.githubusercontent.com/assets/3908213/17294573/0a5a8f38-57f8-11e6-9290-bb0fa4ab90bd.png)

**Comment by y0ssar1an** [comment]
I know for a fact that I'm missing `-webkit-` prefixed properties, values, functions, pseudo-classes, and pseudo-elements. I was able to find relatively authoritative lists of `-moz-` and `-ms-` prefixed CSS features, but not for `-webkit-`.

My criteria for including a prefixed feature is simply that the feature must be on the standards track. In other words, it must be described in a W3C spec. If you look at [Mozilla's list of prefixes](https://developer.mozilla.org/en-US/docs/Web/CSS/Mozilla_Extensions), you can see they clearly distinguish between the standards track and non-standard features.
>Proprietary Mozilla-prefixed properties (do not use on Web sites)

I have to go to work right now, but I'll research the `-webkit-` gradient syntax as soon as I can, and hopefully have a solution for your shortly. Thanks for taking the time to open this issue!

**Comment by y0ssar1an** [comment]
[I did some research](https://css-tricks.com/css3-gradients/) and it looks like the `-webkit-gradient(linear, ...)` syntax is a very old version of the gradient syntax. It's not needed unless you have to support some ancient browsers. The newer variant would be `-webkit-linear-gradient()`, where the prefix is only necessary for [the Android browser up to 4.3](http://caniuse.com/#feat=css-gradients), as you pointed out.

Since the `-webkit-gradient()` syntax is thoroughly obsolete, and the `-webkit-linear-gradient()` syntax is required by less than 1% of browsers, I don't think either should be highlighted by CSS3. I'd recommend changing the code to `-webkit-linear-gradient()`, or just using it in unprefixed form.
