### ISSUE TITLE
Remove stray semicolon matching for better interop with CSS Frameworks?

### ISSUE THREAD

**Issue by nirfse** [y0ssar1an/CSS3#70]
**Problem and feature request:**
Currently it's not possible to set user's custom CSS syntax rules in Sublime's `Preferences 🡪 Package Settings 🡪 CSS3 🡪 Settings - User` menu entry. Please consider implementation.

**Use-case:**
In addition to standard CSS3, many developers are actively using third-party CSS frameworks with custom CSS syntax. For example [Lost Grid](https://github.com/peterramsing/lost). LostGrid provides custom CSS-syntax for grid layout, such as: `@lost gutter 0px`, `lost-column: 1/2 2 40px`, `lost-flex-container: column`, `lost-utility: edit rgb(166, 0, 0)`, and many others.  Currently CSS3 package marks such lines of code with red colon highlighting:

![css3-lostgrid](https://cloud.githubusercontent.com/assets/7230177/20796681/f19b837e-b7df-11e6-9829-69eabae340f3.png)

While CSS3 package can't and shouldn't support syntax for all kinds of various third-party frameworks, it would be useful to add the ability for users to specify their own rule-set to at least ignore custom syntax. It means that CSS3 package would simply ignore highlighting and autocomplete features for those specific rules.  Custom rule settings would look like this:
```...
"ignore_rules:" {
    "by_prefix": "lost-",
    "by_prefix": "@lost"
}
...
```
Thank you for consideration.

**Comment by y0ssar1an** [comment]
Unfortunately, the highlighting of stray braces and semicolons is done by the syntax highlighter, which is constructed by the `CSS3.sublime-syntax` file. This is a YAML file with a bunch of regexes in it. It's completely declarative. There's no way to say something like "if the user has disabled this in the settings, don't highlight stray semicolons."

I can't think of any way to implement this. Even if it were possible, I'd prefer not to add a User Settings file. I like the fact that CSS3 has no knobs to configure.

Maybe stray semicolon matching isn't worth it. ¯\_(ツ)_/¯ I don't write CSS professionally so I don't know how common these frameworks are. I could be convinced to strip it out. I'll leave this issue open to see if more people like the idea.

In the meantime, you can mitigate this by choosing a color scheme that's less noisy about stray semicolons. Here's what they look like in Solarized Dark, for example:

![image](https://cloud.githubusercontent.com/assets/1250684/20862135/bc21f0a6-b957-11e6-837d-49b9bbef47de.png)

**Comment by nirfse** [comment]
Got it, thanks for the clarification. Let's see how others vote.

**Comment by rfgamaral** [comment]
I was coming to this repository posting the same exact issue but in the context of [CSS Modules](https://github.com/css-modules/css-modules), which looks like this on Sublime with CSS3 plugin:

![image](https://cloud.githubusercontent.com/assets/96476/22090053/2bc1a51a-dde7-11e6-8645-37c54466bffc.png)

> Maybe stray semicolon matching isn't worth it. ¯_(ツ)_/¯ I don't write CSS professionally so I don't know how common these frameworks are. I could be convinced to strip it out. I'll leave this issue open to see if more people like the idea.

I'm confused... What exactly would it mean - in terms of syntax highlighting - to strip out the stray semicolon? Could you give examples?

> Unfortunately, the highlighting of stray braces and semicolons is done by the syntax highlighter, which is constructed by the CSS3.sublime-syntax file. This is a YAML file with a bunch of regexes in it. It's completely declarative.

Instead of having options to disable certain matches, would it be possible to add our own regexes to match custom rules for these frameworks?

**Comment by y0ssar1an** [comment]
>I'm confused... What exactly would it mean - in terms of syntax highlighting - to strip out the stray semicolon? Could you give examples?

By "stray semicolon" and "stray brace", I mean an additional semicolon or brace that was added by mistake.
![image](https://cloud.githubusercontent.com/assets/1250684/22187302/d653186e-e0b8-11e6-951d-1500701d55a8.png)
A stray brace will break your code. A stray semicolon is usually harmless. Usually when you see it, it means you mistyped a property name.

CSS3 helpfully highlights these mistakes. (Technically, CSS3 is just labelling them as `stray-brace` or `stray-semicolon` and your color scheme is making them bright red, or blue, or whatever). Unfortunately, nonstandard CSS frameworks/modules will also cause innocent semicolons to be labelled as "stray." Basically, the highlighter is saying "I don't recognize this property, so I'm interpreting that semicolon as a stray semicolon."

The question is whether these non-standard frameworks are important enough to justify disabling stray semicolon matching. If they're popular enough, the answer is yes. Otherwise, more people will benefit from leaving stray semicolon matching enabled.

Because the matching happens at the syntax highlighter level, I can't highlight them conditionally. I can't make a `"match_stray_semicolons": false` setting. Either all stray semicolons are highlighted, or none of them are.

>Instead of having options to disable certain matches, would it be possible to add our own regexes to match custom rules for these frameworks?

Well, you could always fork CSS3 and add custom regexes to the [`properties`](https://github.com/y0ssar1an/CSS3/blob/0bb792875e3fb17d64a09d7693dbefafe3c0571b/CSS3.sublime-syntax#L3081) rule. Or you could convince me that nonstandard framework X is so popular that I should support it here.

**Comment by y0ssar1an** [comment]
It looks like CSS Modules only adds a single [`composes`](https://github.com/css-modules/css-modules#composition) property. Is that right?

**Comment by rfgamaral** [comment]
I've only started using CSS Modules myself this past week so I'm not the best person to answer that but I believe it is so. CSS Modules seem to do a lot of things but on the background, completely transparent for the user. One just use CSS as one normally would, except for the `composes` property. Which can look like this:

```css
composes: className;
```

```css
composes: className;
```

```css
composes: classNameA classNameB;
```

```css
composes: className from "./style.css";
```

I think this is it, but someone please correct me if I'm wrong.

**Comment by aribronstein** [comment]
@rfgamaral - you are correct that is the format for CSS Modules

**Comment by y0ssar1an** [comment]
I've just pushed the [v2.1.5 update](https://github.com/y0ssar1an/CSS3/releases/tag/v2.1.5) which adds support for `composes`. Hopefully that will take care of some annoyances. Sorry it took me so long to investigate CSS Modules!

**Comment by y0ssar1an** [comment]
I'm gonna close this since there hasn't been any more requests to remove stray semicolon matching.
