### ISSUE TITLE
CSS3 vs Emmet

### ISSUE THREAD

**Issue by aristidesfl** [y0ssar1an/CSS3#76]
Any way to get back useful shorthands like `w24 -> width: 24px;`?

**Comment by y0ssar1an** [comment]
Not that I'm aware of. Sorry. ☹️
I'll leave this issue open in case any CSS3 user knows any tricks to enable Emmet completions without making the CSS3 completions unusable.

**Comment by aristidesfl** [comment]
When you say they are unusable, what do you mean more precisely? They don't show up? Or get duplicated?

**Comment by y0ssar1an** [comment]
There are so many more Emmet completions than CSS3 completions that the CSS3 completions get lost in the noise. I guess that's okay if you value Emmet's speed over everything. CSS3 is a little smarter about which completions to offer based on the current cursor location. It's also carefully researched. It will never offer obsolete or deprecated code as a completion (If you ever notice anything obsolete, please open an issue 😄). 

I should say that it's been more than a year since I tested CSS3 with Emmet, so you're welcome to try them out. Just install both packages and leave these keys out of your _Emmet Package Settings - User_ file.
```js
"show_css_completions": false,
"disable_tab_abbreviations_for_scopes": "source.css"
```
You may find that having both sets of completions enabled works just fine for you. I encourage you to try it out and let me know if you think I should still recommend disabling Emmet completions.

**Comment by aristidesfl** [comment]
I've tried this out, and it seems to work fairly well just by removing the emmet completions from the autocomplete popup without disabling tab abbreviations:

```json
{
      "show_css_completions": false
}
```

CSS3 completions take precedence since they are being show on the list but when you type an emmet expressions with a number and press tab, emmet works:

```css
w10 -> width: 10px;
```

Unless I'm missing something, I would suggest that the recommendation of setting `"disable_tab_abbreviations_for_scopes": "source.css"` should be removed from the readme.

**Comment by y0ssar1an** [comment]
Thanks for the research @aristidesfl! I'll test this out and update the README and install instructions as soon as I can.

**Comment by y0ssar1an** [comment]
I played with Emmet for a while and I think you're right. I updated the language in the README and install instructions to soften the recommendation about disabling Emmet completions altogether. Disabling Emmet completions entirely is now _optional_. I'm still recommending that Emmet completions be hidden from the completions menu with `"show_css_completions": false`, though.

Are you satisfied with these changes, or do you think we should do more to clarify the interaction between CSS3 and Emmet?

**Comment by aristidesfl** [comment]
I would not even mention the second option, unless you disclaim as an exception. Emmet is still the most installed Sublime package, and with the 1st option there are no conflicts whatsoever. Maybe explain how they interact together and how yo take advantage of emmet snippets `w24 -> width: 24px;`

**Comment by y0ssar1an** [comment]
Done. Cheers and thanks for the feedback! 🍻
