### ISSUE TITLE
Support for postcss-for and postcss-each?

### ISSUE THREAD

**Issue by amustill** [y0ssar1an/CSS3#82]
The `postcss-cssnext` support is great in this package, but I'm wondering it would be possible to add support the `@for` and `@each` syntax provided by [postcss-for](https://www.npmjs.com/package/postcss-for) and [postcss-each](https://www.npmjs.com/package/postcss-each) respectively?

Obviously this isn't 'true' CSS and falls outside of the CSS spec, but these two standalone packages have a pretty large user base with 13k and 28k installs via NPM in the past month, so I feel it would be a worthwhile addition if possible.

Below is a screenshot of how the highlighting currently appears for these two rules.

<img width="936" alt="postcss-syntax" src="https://user-images.githubusercontent.com/448157/27956683-d372e7b4-6312-11e7-8862-7ff2435a5e0f.png">

**Comment by y0ssar1an** [comment]
Sorry. I feel like if I support `for` and `each`, then I'll have to support everything on [PostCSS](https://github.com/postcss/postcss#plugins). I was okay with supporting `cssnext` because...
1. Most of the work was already done. All I had to add was nested CSS.
2. Everything in `cssnext` is backed by a W3C spec.

As you mentioned, `for` and `each` fall outside the specs. Also, nested CSS blocks are really tricky to get right. The more nested blocks I support, the harder it will be to debug when highlighting or completions aren't working right.

So I'm sorry I can't add this, but thanks for raising the issue! It was worthwhile to research. I'm not a front-end guy, so the way I find out about new and interesting CSS is from users like yourself 🙂
