### ISSUE TITLE
CSS comments within HTML code

### ISSUE THREAD

**Issue by FeBe95** [y0ssar1an/CSS3#91]
Hi, I noticed that the CSS default comment syntax `/* */` is not working anymore when writing code in the style tag of HTML code. Hitting <kbd>ctrl</kbd>+<kbd>/</kbd> gives:

```
<style type="text/css">
    body {
        <!-- background-color: red; -->
    }
</style>
```

This happens due to the changes made to this file:
[Comments.tmPreferences](https://github.com/y0ssar1an/CSS3/commit/a7c0d6b64c26fff95dcf9806adaf9c492645ad0d#diff-91fb31a24e75a7f787ffeb0399c0d8c9)
Was this change necessary in order to make something else work?

**Comment by y0ssar1an** [comment]
Thank you very much for reporting this! Investigating this has been educational.

I can't quite remember why I added `-text.html` to `Comments.tmPreferences`, but the commit message leaves this clue.
>Don't insert /* CSS comments */ when with super+/ when in HTML.
I assume this was fixing a bug.

In any case, it turns out that it isn't the reason why HTML comments don't work inside `<style>` blocks. This is what's happening:
1. The Sublime HTML syntax definition recognizes the `<style>` tag (which BTW does not require `type=text/css` in HTML5).
2. The Sublime HTML syntax definition passes control to the syntax definition that has registered the `source.css` scope. If you've followed my installation instructions and disabled the default CSS package, CSS3 will be the only syntax definition that has registered `source.css`.
3. CSS3 will highlight the contents of the `<style>` block, but it doesn't have any rules for matching HTML comments, so it skips right over the `<!--` and `-->`.
4. The `<style>` block ends, and control returns to the default HTML package.

So the question is: should CSS3 have a rule for matching HTML comments? Are HTML comments valid inside `<style>` blocks? As far as I can tell, the answer is that [they're permitted, but not recommended](https://developer.mozilla.org/en-US/docs/Web/CSS/Comments#Notes). The most recent spec I can find referencing this is the CSS 2.1 spec.
>CSS also allows the SGML comment delimiters ("") in certain places defined by the grammar, but they do not delimit CSS comments. They are permitted so that style rules appearing in an HTML source document (in the STYLE element) may be hidden from pre-HTML 3.2 user agents. See the HTML 4 specification ([HTML4]) for more information.
>https://www.w3.org/TR/CSS2/syndata.html#comments

So they're acceptable as a way of hiding CSS rules from ancient web browsers. Modern browsers will just ignore them and apply the style rule anyway. I tested this in Chrome's Dev Tools. Adding a `<!--` seemed to have no effect, meaning the browser was ignoring it. (DISCLAIMER: I'm not a front-end person. I'd appreciate some outside testing to verify my assumptions that browsers ignore `<!--` in style blocks).

_I think_ the current behavior might be correct. The way it's highlighting `background: red;` in your example gives an accurate impression of how the browser is interpreting the code.

**Comment by FeBe95** [comment]
> I think the current behavior might be correct.

When a user hits <kbd>ctrl</kbd>+<kbd>/</kbd> he most likely wants to comment out the line(s) of CSS code, so that should be the "ultimate" purpose of the shortcut.

For me both Chrome and Firefox don't ignore a HTML comment in a style tag and therefore don't apply the affected rules, but I think that it is just not the correct way of commenting CSS code.
Also hitting <kbd>ctrl</kbd>+<kbd>/</kbd> multiple times adds more and more HTML comments instead of toggling it, because Sublime doesn't understand what to do with `<!-- foo bar -->` in CSS code and assumes the symbols are just random text that the user wants to comment out.
My current solution is a seperate Comments.tmPreferences file in a subfolder named "CSS3" in the Packages folder of Sublime. It is identical with yours apart from the ` -text.html` part that I removed and overrides your packaged file.
So yes, HTML Comments still are undetected within the style tags but that doesn't matter anymore because the keyboard shortcut gives the _correct_ comments again.

**Comment by y0ssar1an** [comment]
After some more testing, I've removed `-text.html` from `Comments.tmPreferences`. The update should land on Package Control in an hour. Thanks for the investigation and for your patience!

The new behavior will occasionally produce funny results. If you put the cursor to the right of a `<style>|` block and press <kbd>Ctrl</kbd><kbd>/</kbd>, you will get this:
```html
/* <style> */
```
Even though the text is HTML, the cursor is located inside a CSS-scoped block, so Sublime chooses the `/*` comments. That's not a big deal, and the behavior is predictable. Wherever the cursor is located, that's the comment style you're going to get.

I think removing `-text.html` solves more problems than it creates and I thank you for raising this issue.
